# Generated by Django 4.1.7 on 2024-02-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='is_deleted',
        ),
    ]
